#!usr/bin/python

a = input("a = ")
b = input ("b = ")
print('Tong 2 so a va b: ')
print(a+b)
print('Hieu cua 2 so a va b: ')
print(a-b)
print('Tich cua 2 so a va b: ')
print(a*b)
print('Thuong cua 2 so a va b: ')
print(a/b)
print('Ket qua cua a va b: ')
print(a%b)
print('Luy thua cua a va b: ')
print(a**b)
